# Generated by Django 4.2.4 on 2023-08-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_country_name', models.CharField(max_length=255)),
                ('user_city_name', models.CharField(max_length=255)),
                ('user_country_code', models.CharField(max_length=255)),
                ('user_city_code', models.CharField(max_length=255)),
            ],
        ),
    ]
